version: '3'

services: 
    node:
        container_name: node
        build: .
        links:
            - mongo
        depends_on: 
            - mongo
        ports: 
            - '3000:3000'
        volumes: 
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        command: npm start
    mongo:
        container_name: mongo
        image: mongo:4.4.7-focal
        volumes: 
            - ./data:/data/db
        ports: 
            - '2717:27017'
        